<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ad155f8f1cf0d418fe49e248db8c661b' => $vendorDir . '/react/promise/src/functions_include.php',
    '972fda704d680a3a53c68e34e193cb22' => $vendorDir . '/react/promise-timer/src/functions_include.php',
    '7b11c4dc42b3b3023073cb14e519683c' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    'a0edc8309cc5e1d60e3047b5df6b7052' => $vendorDir . '/guzzlehttp/psr7/src/functions_include.php',
    'fad373d645dd668e85d44ccf3c38fbd6' => $vendorDir . '/guzzlehttp/streams/src/functions.php',
    '154e0d165f5fe76e8e9695179d0a7345' => $vendorDir . '/guzzlehttp/guzzle/src/functions.php',
    '2c6da23fe52a0f3086a902a594e0aee0' => $vendorDir . '/greenfieldtech-nirs/phpari/phpari.php',
    '7525a36fd9254cfd3cb9bb7e222857ad' => $vendorDir . '/greenfieldtech-nirs/phpari/phpari_config.php',
    'b835d2b63007c79e45fe8b0534b1861b' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/asterisk.php',
    '9805b55e0ceb71474a9c7b00c2923258' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/channels.php',
    'cfda8041a1c5a4d566de4c88070a3b60' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/bridges.php',
    '1f69d111489517ea7560a23a2d0e3aea' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/endpoints.php',
    'b4cc0b1a22853af28663603bef613336' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/recordings.php',
    'c0b0bba9b9fce0435a9dbb27357bf0f1' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/applications.php',
    'ae292bfab0e2b749997f90da9cce7df4' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/devicestates.php',
    '19b84a76c3e6bb7de83ec3052d825740' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/events.php',
    'd4ab5f9d1e298944b5172f4ffea63cd4' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/mailboxes.php',
    'b95aad392d21dcf4b463856b5915f6a8' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/sounds.php',
    '4e4f27113c2afa0a1dddbb94d1a3b19f' => $vendorDir . '/greenfieldtech-nirs/phpari/src/interfaces/playbacks.php',
    'af9b31b04311546f31f3c8268326b657' => $vendorDir . '/greenfieldtech-nirs/phpari/src/helpers/parsing_helper.php',
    'e68c5a329e157b94a3f2ea29e5ed98fb' => $vendorDir . '/greenfieldtech-nirs/phpari/src/helpers/config_helper.php',
);
