<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit63f31326cf995b66d69e6336790d5055
{
    public static $files = array (
        'ad155f8f1cf0d418fe49e248db8c661b' => __DIR__ . '/..' . '/react/promise/src/functions_include.php',
        '972fda704d680a3a53c68e34e193cb22' => __DIR__ . '/..' . '/react/promise-timer/src/functions_include.php',
        '7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'fad373d645dd668e85d44ccf3c38fbd6' => __DIR__ . '/..' . '/guzzlehttp/streams/src/functions.php',
        '154e0d165f5fe76e8e9695179d0a7345' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions.php',
        '2c6da23fe52a0f3086a902a594e0aee0' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/phpari.php',
        '7525a36fd9254cfd3cb9bb7e222857ad' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/phpari_config.php',
        'b835d2b63007c79e45fe8b0534b1861b' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/asterisk.php',
        '9805b55e0ceb71474a9c7b00c2923258' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/channels.php',
        'cfda8041a1c5a4d566de4c88070a3b60' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/bridges.php',
        '1f69d111489517ea7560a23a2d0e3aea' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/endpoints.php',
        'b4cc0b1a22853af28663603bef613336' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/recordings.php',
        'c0b0bba9b9fce0435a9dbb27357bf0f1' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/applications.php',
        'ae292bfab0e2b749997f90da9cce7df4' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/devicestates.php',
        '19b84a76c3e6bb7de83ec3052d825740' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/events.php',
        'd4ab5f9d1e298944b5172f4ffea63cd4' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/mailboxes.php',
        'b95aad392d21dcf4b463856b5915f6a8' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/sounds.php',
        '4e4f27113c2afa0a1dddbb94d1a3b19f' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/interfaces/playbacks.php',
        'af9b31b04311546f31f3c8268326b657' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/helpers/parsing_helper.php',
        'e68c5a329e157b94a3f2ea29e5ed98fb' => __DIR__ . '/..' . '/greenfieldtech-nirs/phpari/src/helpers/config_helper.php',
    );

    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'Zend\\Validator\\' => 15,
            'Zend\\Uri\\' => 9,
            'Zend\\Stdlib\\' => 12,
            'Zend\\ServiceManager\\' => 20,
            'Zend\\Log\\' => 9,
            'Zend\\Loader\\' => 12,
            'Zend\\Hydrator\\' => 14,
            'Zend\\Http\\' => 10,
            'Zend\\Escaper\\' => 13,
        ),
        'W' => 
        array (
            'WyriHaximus\\React\\Guzzle\\HttpClient\\' => 36,
            'WyriHaximus\\React\\Guzzle\\' => 25,
        ),
        'R' => 
        array (
            'React\\Stream\\' => 13,
            'React\\Socket\\' => 13,
            'React\\SocketClient\\' => 19,
            'React\\Promise\\Timer\\' => 20,
            'React\\Promise\\' => 14,
            'React\\HttpClient\\' => 17,
            'React\\EventLoop\\' => 16,
            'React\\Dns\\' => 10,
            'React\\Cache\\' => 12,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Container\\' => 14,
        ),
        'I' => 
        array (
            'Interop\\Container\\' => 18,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Stream\\' => 18,
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Zend\\Validator\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-validator/src',
        ),
        'Zend\\Uri\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-uri/src',
        ),
        'Zend\\Stdlib\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-stdlib/src',
        ),
        'Zend\\ServiceManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-servicemanager/src',
        ),
        'Zend\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-log/src',
        ),
        'Zend\\Loader\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-loader/src',
        ),
        'Zend\\Hydrator\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-hydrator/src',
        ),
        'Zend\\Http\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-http/src',
        ),
        'Zend\\Escaper\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-escaper/src',
        ),
        'WyriHaximus\\React\\Guzzle\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/wyrihaximus/react-guzzle-http-client/src',
        ),
        'WyriHaximus\\React\\Guzzle\\' => 
        array (
            0 => __DIR__ . '/..' . '/wyrihaximus/react-guzzle/src',
        ),
        'React\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/stream/src',
        ),
        'React\\Socket\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/socket/src',
        ),
        'React\\SocketClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/socket-client/src',
        ),
        'React\\Promise\\Timer\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise-timer/src',
        ),
        'React\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise/src',
        ),
        'React\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/http-client/src',
        ),
        'React\\EventLoop\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/event-loop/src',
        ),
        'React\\Dns\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/dns/src',
        ),
        'React\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/cache/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Interop\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/container-interop/container-interop/src/Interop/Container',
        ),
        'GuzzleHttp\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/streams/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'E' => 
        array (
            'Evenement' => 
            array (
                0 => __DIR__ . '/..' . '/evenement/evenement/src',
            ),
        ),
        'D' => 
        array (
            'Devristo\\Phpws\\' => 
            array (
                0 => __DIR__ . '/..' . '/devristo/phpws/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Pest' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'PestJSON' => __DIR__ . '/..' . '/educoder/pest/PestJSON.php',
        'PestXML' => __DIR__ . '/..' . '/educoder/pest/PestXML.php',
        'PestXML_Exception' => __DIR__ . '/..' . '/educoder/pest/PestXML.php',
        'Pest_BadRequest' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_ClientError' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Conflict' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Curl_Exec' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Curl_Init' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Curl_Meta' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Exception' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Forbidden' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Gone' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_InvalidRecord' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Json_Decode' => __DIR__ . '/..' . '/educoder/pest/PestJSON.php',
        'Pest_Json_Encode' => __DIR__ . '/..' . '/educoder/pest/PestJSON.php',
        'Pest_MethodNotAllowed' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_NotFound' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_ServerError' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_Unauthorized' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
        'Pest_UnknownResponse' => __DIR__ . '/..' . '/educoder/pest/Pest.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit63f31326cf995b66d69e6336790d5055::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit63f31326cf995b66d69e6336790d5055::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit63f31326cf995b66d69e6336790d5055::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit63f31326cf995b66d69e6336790d5055::$classMap;

        }, null, ClassLoader::class);
    }
}
